# Generated by Django 5.0.2 on 2024-02-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
