# Generated by Django 5.0.2 on 2024-02-24 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_rename_name_menu_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='named_url',
        ),
    ]
